apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
stringData:
  # 아래 내용은 다음 kubectl 명령과 동일합니다:
  # kubectl create secret docker-registry harbor-secret \
  #   --docker-server=harbor.mipllab.com \
  #   --docker-username=lw \
  #   --docker-password=Line9876
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.mipllab.com": {
          "username": "lw",
          "password": "Line9876",
          "auth": "bHc6TGluZTk4NzY="
        }
      }
    }
